CREATE TABLE IF NOT EXISTS botstats (
    id BIGINT NOT NULL,
    time timestamp with time zone NOT NULL,
    messagessent BIGINT NOT NULL,
    messagessentself BIGINT NOT NULL,
    storedmessages BIGINT NOT NULL,
    storedmessagetotalsize BIGINT NOT NULL,
    commands BIGINT NOT NULL,
    timetakentotal BIGINT NOT NULL,
    CONSTRAINT pk_botstats PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS combinations (
    id BIGINT NOT NULL,
    element1 VARCHAR(16) NOT NULL,
    element2 VARCHAR(16) NOT NULL,
    element3 VARCHAR(16) NULL,
    result VARCHAR(16) NOT NULL,
    timecreated timestamp with time zone NOT NULL,
    difficulty integer NOT NULL,
    CONSTRAINT pk_combinations PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS currentstats (
    planetid BIGINT NOT NULL,
    newcoins integer NOT NULL,
    messagessent integer NOT NULL,
    messagesuserssent integer NOT NULL,
    laststatupdate timestamp with time zone NOT NULL,
    CONSTRAINT pk_currentstats PRIMARY KEY (planetid)
);


CREATE TABLE IF NOT EXISTS elements (
    id BIGINT NOT NULL,
    name VARCHAR(16) NOT NULL,
    found integer NOT NULL,
    finder_id BIGINT NOT NULL,
    time_created timestamp with time zone NOT NULL,
    CONSTRAINT pk_elements PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS helps (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    message VARCHAR(256) NOT NULL,
    CONSTRAINT pk_helps PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS messages (
    id BIGINT NOT NULL,
    authorid BIGINT NOT NULL,
    memberid BIGINT NOT NULL,
    channelid BIGINT NOT NULL,
    planetid BIGINT NOT NULL,
    planetindex integer NOT NULL,
    content TEXT NULL,
    timesent timestamp with time zone NOT NULL,
    messageindex BIGINT NOT NULL,
    embeddata text NULL,
    mentionsdata text NULL,
    hash bytea NOT NULL,
    isdeleted boolean NOT NULL,
    searchvector tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS planetinfos (
    planetid BIGINT NOT NULL,
    messagesstored integer NOT NULL,
    CONSTRAINT pk_planetinfos PRIMARY KEY (planetid)
);


CREATE TABLE IF NOT EXISTS stats (
    id BIGINT NOT NULL,
    planetid BIGINT NOT NULL,
    newcoins integer NOT NULL,
    messagesuserssent integer NOT NULL,
    messagessent integer NOT NULL,
    time timestamp with time zone NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS suggestions (
    id BIGINT NOT NULL,
    element1 VARCHAR(16) NOT NULL,
    element2 VARCHAR(16) NOT NULL,
    element3 VARCHAR(16) NULL,
    result VARCHAR(16) NOT NULL,
    userid BIGINT NOT NULL,
    timesuggested timestamp with time zone NOT NULL,
    ayes integer NOT NULL,
    nays integer NOT NULL,
    CONSTRAINT pk_suggestions PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS suggestionvotes (
    id BIGINT NOT NULL,
    userid BIGINT NOT NULL,
    suggestionid BIGINT NOT NULL,
    CONSTRAINT pk_suggestionvotes PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS userinvitems (
    id BIGINT NOT NULL,
    userid BIGINT NOT NULL,
    element VARCHAR(16) NOT NULL,
    timefound timestamp with time zone NOT NULL,
    CONSTRAINT pk_userinvitems PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL,
    userid BIGINT NOT NULL,
    planetid BIGINT NOT NULL,
    coins double precision NOT NULL,
    charsthisminute integer NOT NULL,
    pointsthisminute integer NOT NULL,
    totalpoints integer NOT NULL,
    totalchars integer NOT NULL,
    messagexp double precision NOT NULL,
    elementalxp double precision NOT NULL,
    messages integer NOT NULL,
    activeminutes integer NOT NULL,
    lasthourly timestamp with time zone NOT NULL,
    lastsentmessage timestamp with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS dailytasks (
    id BIGINT NOT NULL,
    memberid BIGINT NOT NULL,
    reward integer NOT NULL,
    tasktype integer NOT NULL,
    goal integer NOT NULL,
    done integer NOT NULL,
    lastdayupdated timestamp with time zone NOT NULL,
    CONSTRAINT pk_dailytasks PRIMARY KEY (id),
    CONSTRAINT fk_dailytasks_users_memberid FOREIGN KEY (memberid) REFERENCES users (id) ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS ix_combinations_element1 ON combinations (element1);


CREATE INDEX IF NOT EXISTS ix_combinations_element2 ON combinations (element2);


CREATE INDEX IF NOT EXISTS ix_combinations_element3 ON combinations (element3);


CREATE INDEX IF NOT EXISTS ix_combinations_result ON combinations (result);


CREATE INDEX IF NOT EXISTS ix_dailytasks_memberid ON dailytasks (memberid);


CREATE INDEX IF NOT EXISTS ix_elements_name ON elements (name);


CREATE INDEX IF NOT EXISTS ix_messages_authorid ON messages (authorid);


CREATE INDEX IF NOT EXISTS ix_messages_hash ON messages (hash);


CREATE INDEX IF NOT EXISTS ix_messages_memberid ON messages (memberid);


CREATE INDEX IF NOT EXISTS ix_messages_messageindex ON messages (messageindex);


CREATE INDEX IF NOT EXISTS ix_messages_planetid ON messages (planetid);


CREATE INDEX IF NOT EXISTS ix_messages_planetindex ON messages (planetindex);


CREATE INDEX IF NOT EXISTS ix_messages_searchvector ON messages USING GIN (searchvector);


CREATE INDEX IF NOT EXISTS ix_messages_timesent ON messages (timesent);


CREATE INDEX IF NOT EXISTS ix_stats_planetid ON stats (planetid);


CREATE INDEX IF NOT EXISTS ix_stats_time ON stats (time);


CREATE INDEX IF NOT EXISTS ix_userinvitems_element ON userinvitems (element);


CREATE INDEX IF NOT EXISTS ix_userinvitems_userid ON userinvitems (userid);


